language: go

go:
  - 1.6
  - master

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y swig libopencv-core-dev libopencv-imgproc-dev libopencv-highgui-dev

script:
  - ! gofmt -d *.go 2>&1 | read
  - go vet
  - go test -v
