language: go

go:
  - 1.6
  - master

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libopencv-dev libopencv-core-dev libopencv-imgproc-dev libopencv-highgui-dev
  - mkdir opencv \
    && cd opencv \
    && wget https://github.com/Itseez/opencv/archive/3.0.0-beta.zip \
    && unzip 3.0.0-beta.zip \
    && cd opencv-3.0.0-beta \
    && mkdir build \
    && cd build \
    && cmake -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=/usr/local -D WITH_TBB=ON -D BUILD_NEW_PYTHON_SUPPORT=ON -D WITH_V4L=ON -D WITH_QT=ON -D WITH_OPENGL=ON .. \
    && make \
    && sudo make install \
    && sudo /bin/bash -c 'echo &amp;quot;/usr/local/lib&amp;quot; &amp;gt; /etc/ld.so.conf.d/opencv.conf' \
    && sudo ldconfig

script:
  - ! gofmt -d *.go 2>&1 | read
  - go vet
  - go test -v
